version: '3.8'

volumes:
    prometheus_data: {}
    api:
    sqlite:

networks:
  API-network:
    driver: bridge


services:
  prometheus:
    image: prom/prometheus
    volumes:
    - './prometheus/:/etc/prometheus'
    - 'prometheus_data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
    - 9090:9090
    restart: always
    networks:
      - API-network


  exporter_1:
    build:
      context: exporter
    image: exporter
    environment:
      RAND_SEED: 1

  exporter_2:
    build:
      context: exporter
    image: exporter
    environment:
      RAND_SEED: 2

  exporter_3:
    build:
      context: exporter
    image: exporter
    environment:
      RAND_SEED: 3

  backend-api:
    container_name: Skillz-backend
    build: API
    environment:
      DB_DRIVER: sqlite
      GIN_MODE: debug
      PORT: ${PORT}
      PROMETHEUS_URL: "prometheus:9090"
      API_SECRET: ${API_SECRET}
      DB_NAME: ${DB_SQLITE_NAME}
    ports:
      - 8080:${PORT}
    restart: on-failure
    volumes:
      - api:/api
      - sqlite:/database
    networks:
      - API-network
